[package]
name = "nia-body-check"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true

[dependencies]
nia-ast.workspace = true
nia-body-ir.workspace = true
nia-comptime-check.workspace = true
nia-comptime-engine.workspace = true
nia-comptime-ir.workspace = true
nia-defs.workspace = true
nia-diagnostic.workspace = true
nia-ids.workspace = true
nia-item-signatures.workspace = true
nia-layout.workspace = true
nia-local-resolve.workspace = true
nia-node-id.workspace = true
nia-source.workspace = true
nia-span.workspace = true
nia-static-ir.workspace = true
nia-target-config.workspace = true
nia-trait-solve.workspace = true
nia-ty.workspace = true
nia-type-lower.workspace = true
nia-type-normalize.workspace = true
nia-value-resolve.workspace = true

[dev-dependencies]
nia-parser.workspace = true
nia-syntax.workspace = true
nia-target-config.workspace = true
nia-type-resolve.workspace = true

[lib]
path = "src/lib.rs"
