[package]
name = "nia-build"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true

[features]
default = ["llvm-dynamic"]
llvm-dynamic = ["nia-driver/llvm-dynamic"]
llvm-static = ["nia-driver/llvm-static"]

[dependencies]
libc.workspace = true
nia-compat.workspace = true
nia-compiler-query.workspace = true
nia-driver = { workspace = true, default-features = false }
nia-imports.workspace = true
nia-loader-query.workspace = true
nia-linker.workspace = true
nia-query.workspace = true
nia-source.workspace = true
nia-target-config.workspace = true
nia-timing.workspace = true
nia-toolchain.workspace = true

[lib]
path = "src/lib.rs"
