[package]
name = "nia-build"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true

[dependencies]
libc.workspace = true
nia-compiler-query.workspace = true
nia-driver.workspace = true
nia-imports.workspace = true
nia-loader-query.workspace = true
nia-query.workspace = true
nia-source.workspace = true
nia-target-config.workspace = true
nia-timing.workspace = true
nia-toolchain.workspace = true

[lib]
path = "src/lib.rs"
