[package]
name = "nia-llvm"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true

[features]
default = ["llvm-dynamic"]
llvm-dynamic = ["llvm-sys/prefer-dynamic"]
llvm-static = ["llvm-sys/force-static"]

[dependencies]
nia-diagnostic.workspace = true
nia-ice.workspace = true
nia-span.workspace = true
llvm-sys.workspace = true

[lib]
path = "src/lib.rs"
