[package]
name = "nia-type-resolve"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true

[dependencies]
nia-ast.workspace = true
nia-ast-walk.workspace = true
nia-defs.workspace = true
nia-diagnostic.workspace = true
nia-ids.workspace = true
nia-imports.workspace = true
nia-item-tree.workspace = true
nia-node-id.workspace = true
nia-span.workspace = true
nia-symbol.workspace = true
nia-ty.workspace = true

[dev-dependencies]
nia-parser.workspace = true
nia-symbol-table.workspace = true

[lib]
path = "src/lib.rs"
