use std::fmt::Write as _;
use std::fs;
use std::path::{Path, PathBuf};

use super::Language;
use crate::MaintainResult;

pub(super) const GENERATOR_IDENTITY: &str = "competitive_synthetic";

pub(super) const fn expected_total(leaf_modules: usize) -> u64 {
    let modules = leaf_modules as u64;
    2 * modules * modules + 5 * modules
}

fn module_name(index: usize) -> String {
    format!("m{index:03}")
}

fn nia_module(index: usize) -> String {
    format!(
        "const INDEX: i64 = {index}i64;\n\
         const fn derive(seed: i64) i64 {{ seed * 3i64 + 7i64 }}\n\
         const DERIVED: i64 = derive(INDEX);\n\n\
         struct Marker {{\n    value: i64,\n}}\n\n\
         fn identity[T](value: T) T {{ value }}\n\n\
         pub fn value() i64 {{\n\
             let marker = identity(Marker {{ value: DERIVED + INDEX }});\n\
             marker.value\n\
         }}\n"
    )
}

fn rust_module(index: usize) -> String {
    format!(
        "const INDEX: i64 = {index};\n\
         const fn derive(seed: i64) -> i64 {{ seed * 3 + 7 }}\n\
         const DERIVED: i64 = derive(INDEX);\n\n\
         struct Marker {{\n    value: i64,\n}}\n\n\
         fn identity<T>(value: T) -> T {{ value }}\n\n\
         pub fn value() -> i64 {{\n\
             identity(Marker {{ value: DERIVED + INDEX }}).value\n\
         }}\n"
    )
}

fn zig_module(index: usize) -> String {
    format!(
        "const index: i64 = {index};\n\
         fn derive(comptime seed: i64) i64 {{ return seed * 3 + 7; }}\n\
         const derived: i64 = derive(index);\n\n\
         const Marker = struct {{\n    value: i64,\n}};\n\n\
         fn identity(input: anytype) @TypeOf(input) {{ return input; }}\n\n\
         pub fn value() i64 {{\n\
             return identity(Marker{{ .value = derived + index }}).value;\n\
         }}\n"
    )
}

fn nia_root(leaf_modules: usize) -> String {
    let mut source = String::from("// Generated by competitive_synthetic.\n");
    for index in 0..leaf_modules {
        writeln!(source, "pub module {};", module_name(index)).expect("writing to String");
    }
    source.push('\n');
    for index in 0..leaf_modules {
        writeln!(source, "using entry::{};", module_name(index)).expect("writing to String");
    }
    source.push_str(
        "using std::io;\nusing std::process;\nusing process::{Init, ExitCode};\n\n\
         pub fn main(init: Init) ExitCode!() {\n\
             _ = init;\n\
             let mut total: i64 = 0i64;\n",
    );
    for index in 0..leaf_modules {
        writeln!(source, "    total += {}::value();", module_name(index))
            .expect("writing to String");
    }
    writeln!(
        source,
        "    if total != {}i64 {{ return ExitCode(1)!; }}",
        expected_total(leaf_modules)
    )
    .expect("writing to String");
    source.push_str("    io::debugPrint(&\"synthetic-ok\\n\", &[]).?;\n    !()\n}\n");
    source
}

fn rust_root(leaf_modules: usize) -> String {
    let mut source = String::from("// Generated by competitive_synthetic.\n");
    for index in 0..leaf_modules {
        writeln!(source, "mod {};", module_name(index)).expect("writing to String");
    }
    source.push_str("\nfn main() {\n    let mut total: i64 = 0;\n");
    for index in 0..leaf_modules {
        writeln!(source, "    total += {}::value();", module_name(index))
            .expect("writing to String");
    }
    writeln!(
        source,
        "    assert_eq!(total, {});",
        expected_total(leaf_modules)
    )
    .expect("writing to String");
    source.push_str("    println!(\"synthetic-ok\");\n}\n");
    source
}

fn zig_root(leaf_modules: usize) -> String {
    let mut source =
        String::from("// Generated by competitive_synthetic.\nconst std = @import(\"std\");\n");
    for index in 0..leaf_modules {
        let name = module_name(index);
        writeln!(source, "const {name} = @import(\"{name}.zig\");").expect("writing to String");
    }
    source.push_str("\npub fn main() !void {\n    var total: i64 = 0;\n");
    for index in 0..leaf_modules {
        writeln!(source, "    total += {}.value();", module_name(index))
            .expect("writing to String");
    }
    writeln!(
        source,
        "    if (total != {}) return error.InvalidSyntheticTotal;",
        expected_total(leaf_modules)
    )
    .expect("writing to String");
    source.push_str(
        "    const io = std.Io.Threaded.global_single_threaded.io();\n\
             var buffer: [64]u8 = undefined;\n\
             var writer = std.Io.File.stdout().writer(io, &buffer);\n\
             try writer.interface.writeAll(\"synthetic-ok\\n\");\n\
             try writer.interface.flush();\n\
         }\n",
    );
    source
}

pub(super) fn generate(
    destination: &Path,
    language: Language,
    leaf_modules: usize,
) -> MaintainResult<PathBuf> {
    if leaf_modules == 0 {
        return Err("synthetic corpus requires at least one leaf module".to_owned());
    }
    fs::create_dir_all(destination)
        .map_err(|error| format!("failed to create {}: {error}", destination.display()))?;
    let (extension, root) = match language {
        Language::Nia => ("nia", nia_root(leaf_modules)),
        Language::Rust => ("rs", rust_root(leaf_modules)),
        Language::Zig => ("zig", zig_root(leaf_modules)),
    };
    let entry = destination.join(format!("main.{extension}"));
    fs::write(&entry, root)
        .map_err(|error| format!("failed to write {}: {error}", entry.display()))?;
    for index in 0..leaf_modules {
        let source = match language {
            Language::Nia => nia_module(index),
            Language::Rust => rust_module(index),
            Language::Zig => zig_module(index),
        };
        let path = destination.join(format!("{}.{extension}", module_name(index)));
        fs::write(&path, source)
            .map_err(|error| format!("failed to write {}: {error}", path.display()))?;
    }
    Ok(entry)
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::TemporaryDirectory;

    #[test]
    fn total_matches_generated_per_module_values() {
        for count in [1, 10, 50, 100, 500] {
            let actual = (0..count).map(|index| 4 * index as u64 + 7).sum::<u64>();
            assert_eq!(expected_total(count), actual);
        }
    }

    #[test]
    fn every_language_generates_one_root_and_the_requested_leaf_modules() {
        for language in [Language::Nia, Language::Rust, Language::Zig] {
            let temporary = TemporaryDirectory::new("nia-synthetic-test-").unwrap();
            let entry = generate(temporary.path(), language, 3).unwrap();
            assert!(entry.is_file());
            assert_eq!(fs::read_dir(temporary.path()).unwrap().count(), 4);
            let root = fs::read_to_string(entry).unwrap();
            assert!(root.contains("competitive_synthetic"));
            assert!(root.contains("synthetic-ok"));
            assert!(root.contains("m002"));
            assert!(root.contains(&expected_total(3).to_string()));
        }
    }
}
