use std::fmt::Write as _;
use std::fs;
use std::path::{Path, PathBuf};

use super::Language;
use crate::MaintainResult;

pub(super) const GENERATOR_IDENTITY: &str = "competitive_synthetic";

pub(super) const fn expected_total(leaf_modules: usize) -> u64 {
    let modules = leaf_modules as u64;
    2 * modules * modules + 5 * modules
}

fn module_name(index: usize) -> String {
    format!("m{index:03}")
}

fn nia_module(index: usize, edited: bool) -> String {
    let adjustment = if edited { " + 1i64" } else { "" };
    format!(
        "const INDEX: i64 = {index}i64;\n\
         const fn derive(seed: i64) i64 {{ seed * 3i64 + 7i64 }}\n\
         const DERIVED: i64 = derive(INDEX);\n\n\
         struct Marker {{\n    value: i64,\n}}\n\n\
         fn identity[T](value: T) T {{ value }}\n\n\
         pub fn value() i64 {{\n\
             let marker = identity(Marker {{ value: DERIVED + INDEX }});\n\
             marker.value{adjustment}\n\
         }}\n"
    )
}

fn rust_module(index: usize, edited: bool) -> String {
    let adjustment = if edited { " + 1" } else { "" };
    format!(
        "const INDEX: i64 = {index};\n\
         const fn derive(seed: i64) -> i64 {{ seed * 3 + 7 }}\n\
         const DERIVED: i64 = derive(INDEX);\n\n\
         struct Marker {{\n    value: i64,\n}}\n\n\
         fn identity<T>(value: T) -> T {{ value }}\n\n\
         pub fn value() -> i64 {{\n\
             identity(Marker {{ value: DERIVED + INDEX }}).value{adjustment}\n\
         }}\n"
    )
}

fn zig_module(index: usize, edited: bool) -> String {
    let adjustment = if edited { " + 1" } else { "" };
    format!(
        "const index: i64 = {index};\n\
         fn derive(comptime seed: i64) i64 {{ return seed * 3 + 7; }}\n\
         const derived: i64 = derive(index);\n\n\
         const Marker = struct {{\n    value: i64,\n}};\n\n\
         fn identity(input: anytype) @TypeOf(input) {{ return input; }}\n\n\
         pub fn value() i64 {{\n\
             return identity(Marker{{ .value = derived + index }}).value{adjustment};\n\
         }}\n"
    )
}

fn nia_root(leaf_modules: usize, accepts_leaf_edit: bool) -> String {
    let mut source = String::from("// Generated by competitive_synthetic.\n");
    for index in 0..leaf_modules {
        writeln!(source, "pub module {};", module_name(index)).expect("writing to String");
    }
    source.push('\n');
    for index in 0..leaf_modules {
        writeln!(source, "using entry::{};", module_name(index)).expect("writing to String");
    }
    source.push_str(
        "using std::io;\nusing std::process;\nusing process::{Init, ExitCode};\n\n\
         pub fn main(init: Init) ExitCode!() {\n\
             _ = init;\n\
             let mut total: i64 = 0i64;\n",
    );
    for index in 0..leaf_modules {
        writeln!(source, "    total += {}::value();", module_name(index))
            .expect("writing to String");
    }
    let total = expected_total(leaf_modules);
    if accepts_leaf_edit {
        writeln!(source, "    if total == {total}i64 {{").expect("writing to String");
        source.push_str(
            "        io::debugPrint(&\"synthetic-ok\\n\", &[]).?;\n\
             return !();\n\
         }\n",
        );
        writeln!(
            source,
            "    if total != {}i64 {{ return ExitCode(1)!; }}",
            total + 1
        )
        .expect("writing to String");
        source.push_str("    io::debugPrint(&\"synthetic-edited\\n\", &[]).?;\n    !()\n}\n");
    } else {
        writeln!(
            source,
            "    if total != {total}i64 {{ return ExitCode(1)!; }}"
        )
        .expect("writing to String");
        source.push_str("    io::debugPrint(&\"synthetic-ok\\n\", &[]).?;\n    !()\n}\n");
    }
    source
}

fn rust_root(leaf_modules: usize, accepts_leaf_edit: bool) -> String {
    let mut source = String::from("// Generated by competitive_synthetic.\n");
    for index in 0..leaf_modules {
        writeln!(source, "mod {};", module_name(index)).expect("writing to String");
    }
    source.push_str("\nfn main() {\n    let mut total: i64 = 0;\n");
    for index in 0..leaf_modules {
        writeln!(source, "    total += {}::value();", module_name(index))
            .expect("writing to String");
    }
    let total = expected_total(leaf_modules);
    if accepts_leaf_edit {
        writeln!(
            source,
            "    match total {{ {total} => println!(\"synthetic-ok\"), {} => println!(\"synthetic-edited\"), _ => panic!(\"invalid synthetic total\") }}",
            total + 1
        )
        .expect("writing to String");
        source.push_str("}\n");
    } else {
        writeln!(source, "    assert_eq!(total, {total});").expect("writing to String");
        source.push_str("    println!(\"synthetic-ok\");\n}\n");
    }
    source
}

fn zig_root(leaf_modules: usize, accepts_leaf_edit: bool) -> String {
    let mut source =
        String::from("// Generated by competitive_synthetic.\nconst std = @import(\"std\");\n");
    for index in 0..leaf_modules {
        let name = module_name(index);
        writeln!(source, "const {name} = @import(\"{name}.zig\");").expect("writing to String");
    }
    source.push_str("\npub fn main() !void {\n    var total: i64 = 0;\n");
    for index in 0..leaf_modules {
        writeln!(source, "    total += {}.value();", module_name(index))
            .expect("writing to String");
    }
    let total = expected_total(leaf_modules);
    if accepts_leaf_edit {
        writeln!(
            source,
            "    const message = switch (total) {{ {total} => \"synthetic-ok\\n\", {} => \"synthetic-edited\\n\", else => return error.InvalidSyntheticTotal }};",
            total + 1
        )
        .expect("writing to String");
    } else {
        writeln!(
            source,
            "    if (total != {total}) return error.InvalidSyntheticTotal;"
        )
        .expect("writing to String");
        source.push_str("    const message = \"synthetic-ok\\n\";\n");
    }
    source.push_str(
        "    const io = std.Io.Threaded.global_single_threaded.io();\n\
             var buffer: [64]u8 = undefined;\n\
             var writer = std.Io.File.stdout().writer(io, &buffer);\n\
             try writer.interface.writeAll(message);\n\
             try writer.interface.flush();\n\
         }\n",
    );
    source
}

pub(super) fn generate(
    destination: &Path,
    language: Language,
    leaf_modules: usize,
) -> MaintainResult<PathBuf> {
    write_sources(destination, language, leaf_modules, false)
}

fn write_sources(
    destination: &Path,
    language: Language,
    leaf_modules: usize,
    accepts_leaf_edit: bool,
) -> MaintainResult<PathBuf> {
    if leaf_modules == 0 {
        return Err("synthetic corpus requires at least one leaf module".to_owned());
    }
    fs::create_dir_all(destination)
        .map_err(|error| format!("failed to create {}: {error}", destination.display()))?;
    let (extension, root) = match language {
        Language::Nia => ("nia", nia_root(leaf_modules, accepts_leaf_edit)),
        Language::Rust => ("rs", rust_root(leaf_modules, accepts_leaf_edit)),
        Language::Zig => ("zig", zig_root(leaf_modules, accepts_leaf_edit)),
    };
    let entry = destination.join(format!("main.{extension}"));
    fs::write(&entry, root)
        .map_err(|error| format!("failed to write {}: {error}", entry.display()))?;
    for index in 0..leaf_modules {
        let source = match language {
            Language::Nia => nia_module(index, false),
            Language::Rust => rust_module(index, false),
            Language::Zig => zig_module(index, false),
        };
        let path = destination.join(format!("{}.{extension}", module_name(index)));
        fs::write(&path, source)
            .map_err(|error| format!("failed to write {}: {error}", path.display()))?;
    }
    Ok(entry)
}

pub(super) fn generate_build_project(
    destination: &Path,
    language: Language,
    leaf_modules: usize,
) -> MaintainResult<PathBuf> {
    let source_dir = destination.join("src");
    let entry = write_sources(&source_dir, language, leaf_modules, true)?;
    let (build_file, contents) = match language {
        Language::Nia => (
            "build.nia",
            "using std::build;\n\
             using std::fs;\n\n\
             pub fn build(b: &mut build::Build) build::Error!() {\n\
                 let rootModule = b.addModule(\n\
                     build::ModuleOptions::init(&\"synthetic\", fs::PathView::init(&\"src/main.nia\")),\n\
                 ).?;\n\
                 let executable = b.addExecutable(\n\
                     build::ExecutableOptions::init(&\"synthetic\", rootModule),\n\
                 ).?;\n\
                 let emit = b.addEmitExecutableStep(&\"synthetic\", executable).?;\n\
                 b.setDefaultStep(emit).?;\n\
                 !()\n\
             }\n"
                .to_owned(),
        ),
        Language::Rust => (
            "Cargo.toml",
            "[package]\n\
             name = \"competitive-synthetic\"\n\
             version = \"0.0.0\"\n\
             edition = \"2024\"\n\
             publish = false\n\n\
             [profile.dev]\n\
             debug = 0\n\n\
             [profile.release]\n\
             opt-level = 2\n\
             debug = 0\n"
                .to_owned(),
        ),
        Language::Zig => (
            "build.zig",
            "const std = @import(\"std\");\n\n\
             pub fn build(b: *std.Build) void {\n\
                 const target = b.standardTargetOptions(.{});\n\
                 const optimize = b.standardOptimizeOption(.{});\n\
                 const executable = b.addExecutable(.{\n\
                     .name = \"synthetic\",\n\
                     .root_module = b.createModule(.{\n\
                         .root_source_file = b.path(\"src/main.zig\"),\n\
                         .target = target,\n\
                         .optimize = optimize,\n\
                     }),\n\
                 });\n\
                 b.installArtifact(executable);\n\
             }\n"
                .to_owned(),
        ),
    };
    let path = destination.join(build_file);
    fs::write(&path, contents)
        .map_err(|error| format!("failed to write {}: {error}", path.display()))?;
    if matches!(language, Language::Rust) {
        let lock = destination.join("Cargo.lock");
        fs::write(
            &lock,
            "# This file is automatically @generated by Cargo.\n\
             # It is not intended for manual editing.\n\
             version = 4\n\n\
             [[package]]\n\
             name = \"competitive-synthetic\"\n\
             version = \"0.0.0\"\n",
        )
        .map_err(|error| format!("failed to write {}: {error}", lock.display()))?;
    }
    Ok(entry)
}

pub(super) fn edit_leaf(
    project: &Path,
    language: Language,
    index: usize,
) -> MaintainResult<PathBuf> {
    let extension = match language {
        Language::Nia => "nia",
        Language::Rust => "rs",
        Language::Zig => "zig",
    };
    let relative = PathBuf::from("src").join(format!("{}.{extension}", module_name(index)));
    let source = match language {
        Language::Nia => nia_module(index, true),
        Language::Rust => rust_module(index, true),
        Language::Zig => zig_module(index, true),
    };
    let path = project.join(&relative);
    fs::write(&path, source)
        .map_err(|error| format!("failed to edit {}: {error}", path.display()))?;
    Ok(relative)
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::TemporaryDirectory;

    #[test]
    fn total_matches_generated_per_module_values() {
        for count in [1, 10, 50, 100, 500] {
            let actual = (0..count).map(|index| 4 * index as u64 + 7).sum::<u64>();
            assert_eq!(expected_total(count), actual);
        }
    }

    #[test]
    fn every_language_generates_one_root_and_the_requested_leaf_modules() {
        for language in [Language::Nia, Language::Rust, Language::Zig] {
            let temporary = TemporaryDirectory::new("nia-synthetic-test-").unwrap();
            let entry = generate(temporary.path(), language, 3).unwrap();
            assert!(entry.is_file());
            assert_eq!(fs::read_dir(temporary.path()).unwrap().count(), 4);
            let root = fs::read_to_string(entry).unwrap();
            assert!(root.contains("competitive_synthetic"));
            assert!(root.contains("synthetic-ok"));
            assert!(root.contains("m002"));
            assert!(root.contains(&expected_total(3).to_string()));
        }
    }

    #[test]
    fn build_projects_edit_exactly_one_leaf_without_touching_the_root() {
        for language in [Language::Nia, Language::Rust, Language::Zig] {
            let temporary = TemporaryDirectory::new("nia-synthetic-build-test-").unwrap();
            let entry = generate_build_project(temporary.path(), language, 3).unwrap();
            let root_before = fs::read_to_string(&entry).unwrap();
            let edited = edit_leaf(temporary.path(), language, 1).unwrap();
            assert_eq!(edited.parent(), Some(Path::new("src")));
            assert!(
                fs::read_to_string(temporary.path().join(edited))
                    .unwrap()
                    .contains("+ 1")
            );
            assert_eq!(fs::read_to_string(entry).unwrap(), root_before);
            assert!(
                temporary
                    .path()
                    .join("src/m000")
                    .with_extension(language.extension())
                    .is_file()
            );
        }
    }
}
