[package]
name = "nia-static-check"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true

[dependencies]
nia-ast.workspace = true
nia-const-check.workspace = true
nia-const-eval.workspace = true
nia-const-ir.workspace = true
nia-defs.workspace = true
nia-diagnostic.workspace = true
nia-ids.workspace = true
nia-item-signatures.workspace = true
nia-item-tree.workspace = true
nia-local-resolve.workspace = true
nia-node-id.workspace = true
nia-sema-ir.workspace = true
nia-span.workspace = true
nia-symbol.workspace = true
nia-symbol-table.workspace = true
nia-target-config.workspace = true
nia-value-resolve.workspace = true

[dev-dependencies]
nia-item-signatures.workspace = true
nia-parser.workspace = true
nia-source.workspace = true
nia-target-config.workspace = true
nia-type-lower.workspace = true
nia-type-normalize.workspace = true
nia-type-resolve.workspace = true

[lib]
path = "src/lib.rs"
