[package]
name = "nia-node-id"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true

[dependencies]
hashbrown.workspace = true
nia-hash.workspace = true
nia-source.workspace = true
nia-span.workspace = true
parking_lot.workspace = true

[lib]
path = "src/lib.rs"
