use std::collections::BTreeSet;
use std::fs;
use std::path::{Path, PathBuf};
use std::process::{Command, Stdio};

use serde_json::{Map, Value, json};

use super::Language;
use super::synthetic::{self, Specification};
use crate::system::machine::machine_metadata;
use crate::system::toolchain::toolchain_identity;
use crate::{MaintainResult, TemporaryDirectory, absolute_path};

#[derive(Debug, Clone)]
/// Inputs controlling compiler performance baseline collection.
pub struct Options {
    /// Compiler executable to measure.
    pub compiler: PathBuf,
    /// Resource root passed to the compiler.
    pub resource_root: PathBuf,
    /// JSON output path.
    pub output: PathBuf,
    /// Number of samples per workload.
    pub repeat: usize,
    /// Whether to build the repository compiler before measuring.
    pub build_compiler: bool,
    /// Optional controlled-runner identity label.
    pub runner_class: Option<String>,
    /// Explicit workload names, or the default workload set when empty.
    pub workloads: Vec<String>,
}

impl Options {
    /// Creates options using repository-standard compiler and resource paths.
    pub fn for_repository(root: &Path) -> Self {
        Self {
            compiler: root.join("target/release/nia"),
            resource_root: root.join("lib"),
            output: root.join("target/nia-perf/baseline.json"),
            repeat: 1,
            build_compiler: true,
            runner_class: None,
            workloads: Vec::new(),
        }
    }
}

/// Generates a deterministic source containing many large codegen buckets.
pub fn large_codegen_source(blob_count: usize, blob_bytes: usize) -> String {
    let mut lines = vec![
        "// Generated by `cargo maintain baseline compiler`.".to_owned(),
        String::new(),
    ];
    for blob in 0..blob_count {
        lines.push(format!(
            "static blob{blob:03}: [u8; {blob_bytes}] = [{}u8; {blob_bytes}];",
            blob % 256
        ));
    }
    lines.push(String::new());
    lines.push("fn main() usize {".to_owned());
    let lengths = (0..blob_count)
        .map(|blob| format!("blob{blob:03}.len()"))
        .collect::<Vec<_>>();
    for (index, chunk) in lengths.chunks(4).enumerate() {
        let prefix = if index == 0 { "    " } else { "        + " };
        lines.push(format!("{prefix}{}", chunk.join(" + ")));
    }
    lines.push("}".to_owned());
    lines.push(String::new());
    lines.join("\n")
}

fn workloads(root: &Path, output: &Path) -> MaintainResult<Vec<(String, Vec<String>)>> {
    let large = output.join("codegen-buckets-large.nia");
    fs::write(&large, large_codegen_source(16, 1024 * 1024))
        .map_err(|error| format!("failed to write {}: {error}", large.display()))?;
    let path = |relative: &str| root.join(relative).to_string_lossy().into_owned();
    let mut workloads = vec![
        (
            "minimal".to_owned(),
            vec!["check".to_owned(), path("benchmarks/minimal.nia")],
        ),
        (
            "std_hello_check".to_owned(),
            vec!["check".to_owned(), path("examples/hello.nia")],
        ),
        (
            "strings_slices".to_owned(),
            vec!["check".to_owned(), path("examples/data.nia")],
        ),
        (
            "array_list".to_owned(),
            vec!["check".to_owned(), path("examples/collections.nia")],
        ),
        (
            "traits".to_owned(),
            vec!["check".to_owned(), path("examples/generic.nia")],
        ),
        (
            "const_eval".to_owned(),
            vec!["check".to_owned(), path("benchmarks/const_heavy.nia")],
        ),
        (
            "module_backend".to_owned(),
            vec![
                "emit".to_owned(),
                "--backend".to_owned(),
                path("examples/modules/main.nia"),
            ],
        ),
        (
            "codegen_buckets".to_owned(),
            vec![
                "emit".to_owned(),
                "--obj".to_owned(),
                path("benchmarks/codegen_buckets.nia"),
                "--out-dir".to_owned(),
                output
                    .join("codegen-buckets")
                    .to_string_lossy()
                    .into_owned(),
            ],
        ),
        (
            "codegen_buckets_large".to_owned(),
            vec![
                "emit".to_owned(),
                "--obj".to_owned(),
                large.to_string_lossy().into_owned(),
                "--out-dir".to_owned(),
                output
                    .join("codegen-buckets-large")
                    .to_string_lossy()
                    .into_owned(),
            ],
        ),
        (
            "emit_exe".to_owned(),
            vec![
                "emit".to_owned(),
                "--exe".to_owned(),
                path("examples/collections.nia"),
                "-o".to_owned(),
                output.join("array_list").to_string_lossy().into_owned(),
            ],
        ),
        (
            "std_hello_exe".to_owned(),
            vec![
                "emit".to_owned(),
                "--exe".to_owned(),
                path("examples/hello.nia"),
                "-o".to_owned(),
                output.join("std-hello").to_string_lossy().into_owned(),
            ],
        ),
    ];
    for module_count in [10, 50, 100, 500] {
        let source_root = output.join(format!("synthetic-{module_count}-modules"));
        let source = synthetic::generate(
            &source_root,
            Language::Nia,
            Specification::flat_star(module_count),
        )?;
        workloads.push((
            format!("synthetic_{module_count}_modules"),
            vec![
                "emit".to_owned(),
                "--exe".to_owned(),
                source.to_string_lossy().into_owned(),
                "-o".to_owned(),
                output
                    .join(format!("synthetic-{module_count}"))
                    .to_string_lossy()
                    .into_owned(),
            ],
        ));
    }
    Ok(workloads)
}

fn command_output(root: &Path, program: &Path, arguments: &[&str]) -> Option<String> {
    let output = Command::new(program)
        .args(arguments)
        .current_dir(root)
        .stderr(Stdio::null())
        .output()
        .ok()?;
    if !output.status.success() {
        return None;
    }
    let value = String::from_utf8_lossy(&output.stdout).trim().to_owned();
    (!value.is_empty()).then_some(value)
}

fn timing_json(stderr: &str) -> MaintainResult<Map<String, Value>> {
    for line in stderr.lines().rev() {
        let Ok(Value::Object(mut report)) = serde_json::from_str(line) else {
            continue;
        };
        if report.get("process").is_some_and(Value::is_object)
            && report.get("timings").is_some_and(Value::is_array)
            && report.get("counters").is_some_and(Value::is_object)
        {
            // The compiler owns the protocol identity. Maintain records the
            // measured payload without adopting that identity as its schema.
            report.remove("release_compatibility");
            return Ok(report);
        }
    }
    Err("compiler did not emit a structured timing report".to_owned())
}

fn normalize_report_paths(value: &mut Value, root: &Path) {
    match value {
        Value::String(text) => *text = text.replace(&root.to_string_lossy().to_string(), "$REPO"),
        Value::Array(values) => {
            for value in values {
                normalize_report_paths(value, root);
            }
        }
        Value::Object(values) => {
            for value in values.values_mut() {
                normalize_report_paths(value, root);
            }
        }
        _ => {}
    }
}

fn counters(report: &Map<String, Value>) -> Option<&Map<String, Value>> {
    report.get("counters")?.as_object()
}

fn require_allocation_instrumentation(report: &Map<String, Value>) -> MaintainResult<()> {
    let counters = counters(report);
    if counters.is_none_or(|values| {
        !values.contains_key("allocator.allocated_bytes")
            || !values.contains_key("allocator.peak_live_bytes")
    }) {
        return Err(
            "compiler timing report has no allocation counters; performance baselines require \
             nia-cli built with `cargo build --release -p nia-cli --features perf-alloc`"
                .to_owned(),
        );
    }
    Ok(())
}

fn require_module_finalization_instrumentation(report: &Map<String, Value>) -> MaintainResult<()> {
    let required = [
        "backend.module_finalization.start_live_bytes",
        "backend.module_finalization.end_live_bytes",
        "backend.module_finalization.peak_live_bytes",
        "backend.module_finalization.peak_growth_bytes",
    ];
    if counters(report).is_none_or(|values| required.iter().any(|name| !values.contains_key(*name)))
    {
        return Err(
            "module_backend timing report has no backend finalization live-window counters"
                .to_owned(),
        );
    }
    Ok(())
}

fn integer_counter(report: &Map<String, Value>, name: &str) -> Option<i64> {
    counters(report)?.get(name)?.as_i64()
}

fn require_codegen_bucket_instrumentation(
    report: &Map<String, Value>,
    minimum_units: i64,
) -> MaintainResult<()> {
    let units = integer_counter(report, "llvm.units");
    let permits = integer_counter(report, "llvm.memory_permits");
    let lanes = integer_counter(report, "llvm.worker_lanes");
    let submissions = integer_counter(report, "llvm.ready_task_submissions");
    let valid = units.is_some_and(|value| value >= minimum_units)
        && permits.is_some_and(|value| value >= minimum_units)
        && lanes.is_some_and(|value| value >= 1 && units.is_some_and(|units| value <= units))
        && submissions.is_some_and(|value| Some(value) == units);
    if !valid {
        return Err(
            "codegen bucket timing report did not compile the required LLVM units through the \
             live ready-task path"
                .to_owned(),
        );
    }
    Ok(())
}

fn require_std_hello_instrumentation(
    report: &Map<String, Value>,
    require_codegen: bool,
) -> MaintainResult<()> {
    let checked_bodies = integer_counter(report, "compiler.checked_bodies");
    let query_executions = integer_counter(report, "query.executions");
    if !checked_bodies.is_some_and(|value| value >= 10)
        || !query_executions.is_some_and(|value| value >= 1_000)
    {
        return Err(
            "std hello workload did not exercise the expected standard-library frontend path"
                .to_owned(),
        );
    }
    if require_codegen {
        require_codegen_bucket_instrumentation(report, 2)?;
    }
    Ok(())
}

fn synthetic_module_count(name: &str) -> Option<i64> {
    match name {
        "synthetic_10_modules" => Some(10),
        "synthetic_50_modules" => Some(50),
        "synthetic_100_modules" => Some(100),
        "synthetic_500_modules" => Some(500),
        _ => None,
    }
}

fn require_synthetic_scale_instrumentation(
    report: &Map<String, Value>,
    module_count: i64,
) -> MaintainResult<()> {
    let loaded_modules = integer_counter(report, "compiler.loaded_modules");
    let query_executions = integer_counter(report, "query.executions");
    let checked_bodies = integer_counter(report, "compiler.checked_bodies");
    let reachable_bodies = integer_counter(report, "compiler.reachable_bodies");
    let llvm_units = integer_counter(report, "llvm.units");
    let ready_submissions = integer_counter(report, "llvm.ready_task_submissions");
    let valid = loaded_modules.is_some_and(|value| value > module_count)
        && query_executions.is_some_and(|value| value > module_count)
        && checked_bodies.is_some_and(|value| value >= module_count)
        && reachable_bodies.is_some_and(|value| value >= module_count)
        && llvm_units.is_some_and(|value| value >= module_count)
        && ready_submissions.is_some_and(|value| Some(value) == llvm_units);
    if !valid {
        return Err(format!(
            "synthetic {module_count}-module timing report did not retain the required module, query, body, and LLVM-unit counters"
        ));
    }
    Ok(())
}

fn command_label(root: &Path, value: &str) -> String {
    let path = Path::new(value);
    if !path.is_absolute() {
        return value.to_owned();
    }
    if let Ok(relative) = path.strip_prefix(root) {
        return Path::new("$REPO")
            .join(relative)
            .to_string_lossy()
            .into_owned();
    }
    if path
        .parent()
        .and_then(Path::file_name)
        .is_some_and(|name| name.to_string_lossy().starts_with("nia-perf-"))
    {
        return Path::new("$TMP")
            .join(path.file_name().unwrap_or_default())
            .to_string_lossy()
            .into_owned();
    }
    value.to_owned()
}

/// Builds the compiler command line shared by every measured workload.
pub fn workload_command(
    compiler: &Path,
    resource_root: &Path,
    arguments: &[String],
) -> Vec<String> {
    vec![
        compiler.to_string_lossy().into_owned(),
        "--resource-root".to_owned(),
        resource_root.to_string_lossy().into_owned(),
        "--timings=detail".to_owned(),
        "--timings-format=json".to_owned(),
    ]
    .into_iter()
    .chain(arguments.iter().cloned())
    .collect()
}

fn run_workload(
    root: &Path,
    compiler: &Path,
    resource_root: &Path,
    name: &str,
    arguments: &[String],
) -> MaintainResult<Map<String, Value>> {
    let command = workload_command(compiler, resource_root, arguments);
    let output = Command::new(&command[0])
        .args(&command[1..])
        .current_dir(root)
        .stdout(Stdio::null())
        .output()
        .map_err(|error| format!("failed to run workload {name:?}: {error}"))?;
    let stderr = String::from_utf8_lossy(&output.stderr);
    if !output.status.success() {
        eprint!("{stderr}");
        return Err(format!(
            "workload {name:?} failed with status {}",
            output.status
        ));
    }
    let mut report = Value::Object(timing_json(&stderr)?);
    normalize_report_paths(&mut report, root);
    let Value::Object(mut report) = report else {
        return Err("normalized compiler timing report is not an object".to_owned());
    };
    require_allocation_instrumentation(&report)?;
    if name == "module_backend" {
        require_module_finalization_instrumentation(&report)?;
    } else if name == "codegen_buckets" {
        require_codegen_bucket_instrumentation(&report, 2)?;
    } else if name == "codegen_buckets_large" {
        require_codegen_bucket_instrumentation(&report, 4)?;
    } else if name == "std_hello_check" {
        require_std_hello_instrumentation(&report, false)?;
    } else if name == "std_hello_exe" {
        require_std_hello_instrumentation(&report, true)?;
    } else if let Some(module_count) = synthetic_module_count(name) {
        require_synthetic_scale_instrumentation(&report, module_count)?;
    }
    report.insert("name".to_owned(), Value::String(name.to_owned()));
    let compiler_label = compiler
        .strip_prefix(root)
        .unwrap_or(compiler)
        .to_string_lossy()
        .into_owned();
    report.insert(
        "command".to_owned(),
        Value::Array(
            std::iter::once(Value::String(compiler_label))
                .chain(
                    arguments
                        .iter()
                        .map(|value| Value::String(command_label(root, value))),
                )
                .collect(),
        ),
    );
    Ok(report)
}

/// Runs compiler workloads and writes a machine-labelled performance baseline.
pub fn run(root: &Path, options: &Options) -> MaintainResult<()> {
    if options.repeat == 0 {
        return Err("--repeat must be at least 1".to_owned());
    }
    let runner_class = options
        .runner_class
        .as_deref()
        .map(str::trim)
        .map(str::to_owned);
    if runner_class.as_deref() == Some("") {
        return Err("--runner-class must not be empty".to_owned());
    }
    let compiler = absolute_path(&options.compiler)?;
    let resource_root = options.resource_root.canonicalize().map_err(|error| {
        format!(
            "resource root is invalid: {}: {error}",
            options.resource_root.display()
        )
    })?;
    if !resource_root.join("toolchain.meta").is_file() {
        return Err(format!(
            "resource root is invalid: {}",
            resource_root.display()
        ));
    }
    let default_compiler = root.join("target/release/nia");
    if options.build_compiler && compiler == default_compiler {
        let status = Command::new("cargo")
            .args([
                "build",
                "--release",
                "-p",
                "nia-cli",
                "--features",
                "perf-alloc",
            ])
            .current_dir(root)
            .status()
            .map_err(|error| format!("failed to build compiler: {error}"))?;
        if !status.success() {
            return Err(format!("compiler build failed with {status}"));
        }
    }
    if !compiler.is_file() {
        return Err(format!("compiler does not exist: {}", compiler.display()));
    }

    let temporary = TemporaryDirectory::new("nia-perf-")?;
    let available = workloads(root, temporary.path())?;
    let known = available
        .iter()
        .map(|(name, _)| name.as_str())
        .collect::<BTreeSet<_>>();
    let selected = if options.workloads.is_empty() {
        available.iter().map(|(name, _)| name.clone()).collect()
    } else {
        options.workloads.clone()
    };
    let unknown = selected
        .iter()
        .filter(|name| !known.contains(name.as_str()))
        .cloned()
        .collect::<BTreeSet<_>>();
    if !unknown.is_empty() {
        return Err(format!(
            "unknown workload(s): {}",
            unknown.into_iter().collect::<Vec<_>>().join(", ")
        ));
    }
    let mut results = Vec::new();
    for iteration in 0..options.repeat {
        for name in &selected {
            eprintln!(
                "perf: iteration {}/{} {name}",
                iteration + 1,
                options.repeat
            );
            let arguments = &available
                .iter()
                .find(|(available, _)| available == name)
                .expect("selected workload exists")
                .1;
            let mut report = run_workload(root, &compiler, &resource_root, name, arguments)?;
            report.insert("iteration".to_owned(), json!(iteration));
            results.push(Value::Object(report));
        }
    }

    let compiler_built_by_baseline = options.build_compiler && compiler == default_compiler;
    let git = Path::new("git");
    let revision = command_output(root, git, &["rev-parse", "HEAD"]);
    let dirty = command_output(root, git, &["status", "--porcelain"]).is_some();
    let version = command_output(root, &compiler, &["--version"]);
    let baseline = json!({
        "compiler": {
            "path": command_label(root, &compiler.to_string_lossy()),
            "resource_root": command_label(root, &resource_root.to_string_lossy()),
            "version": version,
            "revision": revision,
            "dirty": dirty,
        },
        "machine": machine_metadata(runner_class),
        "toolchain": toolchain_identity(root)?,
        "configuration": {
            "compiler_built_by_baseline": compiler_built_by_baseline,
            "compiler_cargo_profile": compiler_built_by_baseline.then_some("release"),
            "compiler_cargo_features": compiler_built_by_baseline.then_some(["perf-alloc"]),
            "nia_profile": "debug",
            "nia_optimization": "O0",
            "project_cache_state": "disabled unless a workload explicitly supplies --cache-dir",
            "os_page_cache_state": "uncontrolled; may be warm",
        },
        "repeat": options.repeat,
        "results": results,
    });
    let output = absolute_path(&options.output)?;
    if let Some(parent) = output.parent() {
        fs::create_dir_all(parent)
            .map_err(|error| format!("failed to create {}: {error}", parent.display()))?;
    }
    let temporary_output = PathBuf::from(format!("{}.tmp", output.to_string_lossy()));
    fs::write(
        &temporary_output,
        format!(
            "{}\n",
            serde_json::to_string_pretty(&baseline)
                .map_err(|error| format!("failed to encode compiler baseline: {error}"))?
        ),
    )
    .map_err(|error| format!("failed to write {}: {error}", temporary_output.display()))?;
    fs::rename(&temporary_output, &output)
        .map_err(|error| format!("failed to publish {}: {error}", output.display()))?;
    println!("{}", output.display());
    Ok(())
}

#[cfg(test)]
mod tests {
    use super::*;

    fn report(counters: Value) -> Map<String, Value> {
        serde_json::from_value(json!({
            "process": {},
            "timings": [],
            "counters": counters
        }))
        .expect("report object")
    }

    #[test]
    fn workload_command_uses_explicit_resource_root() {
        assert_eq!(
            workload_command(
                Path::new("/tool/nia"),
                Path::new("/tool/lib"),
                &["check".to_owned(), "main.nia".to_owned()]
            ),
            [
                "/tool/nia",
                "--resource-root",
                "/tool/lib",
                "--timings=detail",
                "--timings-format=json",
                "check",
                "main.nia"
            ]
        );
    }

    #[test]
    fn timing_json_discards_compiler_release_identity() {
        let report = json!({
            "release_compatibility": 999,
            "process": {},
            "timings": [],
            "counters": {}
        });
        let parsed = timing_json(&report.to_string()).unwrap();
        assert!(parsed.get("release_compatibility").is_none());
    }

    #[test]
    fn validates_required_instrumentation() {
        let allocation = report(json!({
            "allocator.allocated_bytes": 10,
            "allocator.peak_live_bytes": 5,
        }));
        assert!(require_allocation_instrumentation(&allocation).is_ok());
        assert!(require_allocation_instrumentation(&report(json!({}))).is_err());

        let finalization = report(json!({
            "backend.module_finalization.start_live_bytes": 1,
            "backend.module_finalization.end_live_bytes": 1,
            "backend.module_finalization.peak_live_bytes": 1,
            "backend.module_finalization.peak_growth_bytes": 0,
        }));
        assert!(require_module_finalization_instrumentation(&finalization).is_ok());
    }

    #[test]
    fn validates_live_codegen_bucket_path() {
        let valid = report(json!({
            "llvm.units": 4,
            "llvm.memory_permits": 4,
            "llvm.worker_lanes": 2,
            "llvm.ready_task_submissions": 4,
        }));
        assert!(require_codegen_bucket_instrumentation(&valid, 4).is_ok());
        let cached = report(json!({
            "llvm.units": 4,
            "llvm.memory_permits": 4,
            "llvm.worker_lanes": 2,
            "llvm.ready_task_submissions": 3,
        }));
        assert!(require_codegen_bucket_instrumentation(&cached, 4).is_err());
    }

    #[test]
    fn validates_std_hello_frontend_and_codegen_paths() {
        let frontend = report(json!({
            "compiler.checked_bodies": 71,
            "query.executions": 12_779,
        }));
        assert!(require_std_hello_instrumentation(&frontend, false).is_ok());
        assert!(require_std_hello_instrumentation(&frontend, true).is_err());

        let executable = report(json!({
            "compiler.checked_bodies": 82,
            "query.executions": 17_330,
            "llvm.units": 35,
            "llvm.memory_permits": 35,
            "llvm.worker_lanes": 3,
            "llvm.ready_task_submissions": 35,
        }));
        assert!(require_std_hello_instrumentation(&executable, true).is_ok());
    }

    #[test]
    fn validates_synthetic_scale_instrumentation() {
        let valid = report(json!({
            "compiler.loaded_modules": 135,
            "query.executions": 20_000,
            "compiler.checked_bodies": 120,
            "compiler.reachable_bodies": 110,
            "llvm.units": 108,
            "llvm.ready_task_submissions": 108,
        }));
        assert!(require_synthetic_scale_instrumentation(&valid, 100).is_ok());

        for missing in [
            "compiler.loaded_modules",
            "query.executions",
            "compiler.checked_bodies",
            "compiler.reachable_bodies",
            "llvm.units",
            "llvm.ready_task_submissions",
        ] {
            let mut incomplete = valid.clone();
            incomplete
                .get_mut("counters")
                .and_then(Value::as_object_mut)
                .unwrap()
                .remove(missing);
            assert!(require_synthetic_scale_instrumentation(&incomplete, 100).is_err());
        }
    }

    #[test]
    fn compiler_workloads_share_the_competitive_synthetic_generator() {
        let temporary = TemporaryDirectory::new("nia-compiler-workloads-").unwrap();
        let available = workloads(temporary.path(), temporary.path()).unwrap();
        for module_count in [10, 50, 100, 500] {
            let name = format!("synthetic_{module_count}_modules");
            let arguments = &available
                .iter()
                .find(|(available, _)| available == &name)
                .unwrap()
                .1;
            let entry = Path::new(&arguments[2]);
            assert!(entry.is_file());
            assert_eq!(
                entry.file_name().and_then(|name| name.to_str()),
                Some("main.nia")
            );
            assert_eq!(
                fs::read_dir(entry.parent().unwrap()).unwrap().count(),
                module_count + 1
            );
        }
    }

    #[test]
    fn rejects_malformed_or_incomplete_codegen_bucket_counters() {
        for counters in [
            json!({
                "llvm.units": 1,
                "llvm.memory_permits": 1,
                "llvm.worker_lanes": 1,
                "llvm.ready_task_submissions": 1,
            }),
            json!({
                "llvm.units": true,
                "llvm.memory_permits": 4,
                "llvm.worker_lanes": 2,
                "llvm.ready_task_submissions": 4,
            }),
            json!({
                "llvm.units": 4,
                "llvm.memory_permits": 4,
                "llvm.worker_lanes": 5,
                "llvm.ready_task_submissions": 4,
            }),
            json!({
                "llvm.units": 4,
                "llvm.memory_permits": 4,
                "llvm.worker_lanes": 2,
            }),
        ] {
            assert!(require_codegen_bucket_instrumentation(&report(counters), 4).is_err());
        }
    }

    #[test]
    fn rejects_partial_module_finalization_instrumentation() {
        let partial = report(json!({
            "backend.module_finalization.start_live_bytes": 1,
            "backend.module_finalization.end_live_bytes": 1,
            "backend.module_finalization.peak_live_bytes": 1,
        }));
        assert!(require_module_finalization_instrumentation(&partial).is_err());
    }

    #[test]
    fn large_codegen_source_is_stable_and_reachable() {
        let source = large_codegen_source(4, 32);
        assert!(source.contains("static blob003: [u8; 32]"));
        assert!(source.contains("blob000.len() + blob001.len()"));
    }
}
