#!/usr/bin/env python3
"""Run Nia's fixed compiler workloads and write a machine-readable baseline."""

from __future__ import annotations

import argparse
import json
import subprocess
import sys
import tempfile
from collections.abc import Sequence
from dataclasses import dataclass
from pathlib import Path
from typing import TypedDict, cast

from tools.nia_tools.common.json_data import JsonObject, JsonValue, decode_json
from tools.nia_tools.common.machine import MachineMetadata, machine_metadata
from tools.nia_tools.repository import REPOSITORY_ROOT

ROOT = REPOSITORY_ROOT
DEFAULT_COMPILER = ROOT / "target" / "release" / "nia"
DEFAULT_RESOURCE_ROOT = ROOT / "lib"
DEFAULT_OUTPUT = ROOT / "target" / "nia-perf" / "baseline.json"


@dataclass(frozen=True)
class Options:
    compiler: Path
    resource_root: Path
    output: Path
    repeat: int
    build_compiler: bool
    runner_class: str | None
    workloads: tuple[str, ...] | None


class CompilerIdentity(TypedDict):
    path: str
    resource_root: str
    version: str | None
    revision: str | None
    dirty: bool


class CompilerBaseline(TypedDict):
    schema_version: int
    compiler: CompilerIdentity
    machine: MachineMetadata
    repeat: int
    results: list[JsonObject]


def large_codegen_source(blob_count: int = 16, blob_bytes: int = 1024 * 1024) -> str:
    lines = [
        "// Generated by `python3 -m tools baseline compiler`.",
        "",
    ]
    for blob in range(blob_count):
        byte = blob % 256
        lines.append(
            f"static blob{blob:03}: [{blob_bytes}]u8 = [{byte}u8; {blob_bytes}];"
        )
    lines.extend(("", "fn main() usize {"))
    lengths = [f"blob{blob:03}.len()" for blob in range(blob_count)]
    for start in range(0, len(lengths), 4):
        prefix = "    " if start == 0 else "        + "
        lines.append(prefix + " + ".join(lengths[start : start + 4]))
    lines.extend(("}", ""))
    return "\n".join(lines)


def workloads(output_dir: Path) -> dict[str, list[str]]:
    large_codegen_input = output_dir / "codegen-buckets-large.nia"
    large_codegen_input.write_text(large_codegen_source(), encoding="utf-8")
    return {
        "minimal": ["check", str(ROOT / "benchmarks" / "minimal.nia")],
        "strings_slices": ["check", str(ROOT / "examples" / "02_slices_and_strings.nia")],
        "array_list": ["check", str(ROOT / "examples" / "04_array_list.nia")],
        "traits": ["check", str(ROOT / "examples" / "05_traits_generics.nia")],
        "const_eval": ["check", str(ROOT / "benchmarks" / "const_heavy.nia")],
        "module_backend": [
            "emit",
            "--backend",
            str(ROOT / "examples" / "modules" / "main.nia"),
        ],
        "codegen_buckets": [
            "emit",
            "--obj",
            str(ROOT / "benchmarks" / "codegen_buckets.nia"),
            "--out-dir",
            str(output_dir / "codegen-buckets"),
        ],
        "codegen_buckets_large": [
            "emit",
            "--obj",
            str(large_codegen_input),
            "--out-dir",
            str(output_dir / "codegen-buckets-large"),
        ],
        "emit_exe": [
            "emit",
            "--exe",
            str(ROOT / "examples" / "04_array_list.nia"),
            "-o",
            str(output_dir / "array_list"),
        ],
    }


def command_output(args: list[str]) -> str | None:
    try:
        result = subprocess.run(
            args,
            cwd=ROOT,
            check=True,
            stdout=subprocess.PIPE,
            stderr=subprocess.DEVNULL,
            text=True,
        )
    except (OSError, subprocess.CalledProcessError):
        return None
    return result.stdout.strip() or None


def timing_json(stderr: str) -> JsonObject:
    for line in reversed(stderr.splitlines()):
        try:
            value = decode_json(line, "compiler timing report")
        except ValueError:
            continue
        if (
            isinstance(value, dict)
            and type(value.get("schema_version")) is int
            and value["schema_version"] == 1
        ):
            return value
    raise ValueError("compiler did not emit a schema_version=1 timing report")


def normalize_report_paths(value: JsonValue) -> JsonValue:
    if isinstance(value, str):
        return value.replace(str(ROOT), "$REPO")
    if isinstance(value, list):
        return [normalize_report_paths(item) for item in value]
    if isinstance(value, dict):
        return {key: normalize_report_paths(item) for key, item in value.items()}
    return value


def require_allocation_instrumentation(report: JsonObject) -> None:
    counters = report.get("counters", {})
    if not isinstance(counters, dict) or not {
        "allocator.allocated_bytes",
        "allocator.peak_live_bytes",
    }.issubset(counters):
        raise RuntimeError(
            "compiler timing report has no allocation counters; performance "
            "baselines require nia-cli built with `cargo build --release "
            "-p nia-cli --features perf-alloc`"
        )


def require_module_finalization_instrumentation(report: JsonObject) -> None:
    counters = report.get("counters", {})
    required = {
        "backend.module_finalization.start_live_bytes",
        "backend.module_finalization.end_live_bytes",
        "backend.module_finalization.peak_live_bytes",
        "backend.module_finalization.peak_growth_bytes",
    }
    if not isinstance(counters, dict) or not required.issubset(counters):
        raise RuntimeError(
            "module_backend timing report has no backend finalization live-window counters"
        )


def require_codegen_bucket_instrumentation(
    report: JsonObject, minimum_units: int
) -> None:
    counters = report.get("counters", {})

    def count(name: str) -> int | None:
        value = counters.get(name) if isinstance(counters, dict) else None
        return value if isinstance(value, int) and not isinstance(value, bool) else None

    units = count("llvm.units")
    permits = count("llvm.memory_permits")
    worker_lanes = count("llvm.worker_lanes")
    ready_submissions = count("llvm.ready_task_submissions")
    if (
        units is None
        or units < minimum_units
        or permits is None
        or permits < minimum_units
        or worker_lanes is None
        or worker_lanes < 1
        or worker_lanes > units
        or ready_submissions is None
        or ready_submissions != units
    ):
        raise RuntimeError(
            "codegen bucket timing report did not compile the required LLVM units "
            "through the live ready-task path"
        )


def command_label(value: str) -> str:
    path = Path(value)
    if not path.is_absolute():
        return value
    try:
        return str(Path("$REPO") / path.relative_to(ROOT))
    except ValueError:
        if path.parent.name.startswith("nia-perf-"):
            return str(Path("$TMP") / path.name)
        return value


def workload_command(
    compiler: Path, resource_root: Path, args: list[str]
) -> list[str]:
    return [
        str(compiler),
        "--resource-root",
        str(resource_root),
        "--timings=detail",
        "--timings-format=json",
        *args,
    ]


def run_workload(
    compiler: Path, resource_root: Path, name: str, args: list[str]
) -> JsonObject:
    command = workload_command(compiler, resource_root, args)
    result = subprocess.run(
        command,
        cwd=ROOT,
        stdout=subprocess.DEVNULL,
        stderr=subprocess.PIPE,
        text=True,
    )
    if result.returncode != 0:
        sys.stderr.write(result.stderr)
        raise RuntimeError(f"workload {name!r} failed with status {result.returncode}")
    normalized = normalize_report_paths(timing_json(result.stderr))
    if not isinstance(normalized, dict):
        raise ValueError("normalized compiler timing report is not an object")
    report = normalized
    require_allocation_instrumentation(report)
    if name == "module_backend":
        require_module_finalization_instrumentation(report)
    if name == "codegen_buckets":
        require_codegen_bucket_instrumentation(report, 2)
    if name == "codegen_buckets_large":
        require_codegen_bucket_instrumentation(report, 4)
    report["name"] = name
    try:
        compiler_label = str(compiler.relative_to(ROOT))
    except ValueError:
        compiler_label = str(compiler)
    report["command"] = [compiler_label, *(command_label(value) for value in args)]
    return report


def parse_args(arguments: Sequence[str] | None = None) -> Options:
    parser = argparse.ArgumentParser(
        prog="python3 -m tools baseline compiler", description=__doc__
    )
    parser.add_argument("--compiler", type=Path, default=DEFAULT_COMPILER)
    parser.add_argument("--resource-root", type=Path, default=DEFAULT_RESOURCE_ROOT)
    parser.add_argument("--output", type=Path, default=DEFAULT_OUTPUT)
    parser.add_argument("--repeat", type=int, default=1)
    parser.add_argument("--no-build", action="store_true")
    parser.add_argument(
        "--runner-class",
        help=(
            "explicit controlled-runner identity for cross-run comparison; "
            "omit for strict physical CPU matching"
        ),
    )
    parser.add_argument(
        "--workload",
        action="append",
        help="run only this workload; may be passed more than once",
    )
    namespace = parser.parse_args(arguments)
    if not isinstance(namespace.compiler, Path):
        raise TypeError("argparse did not produce a Path for --compiler")
    if not isinstance(namespace.resource_root, Path):
        raise TypeError("argparse did not produce a Path for --resource-root")
    if not isinstance(namespace.output, Path):
        raise TypeError("argparse did not produce a Path for --output")
    if not isinstance(namespace.repeat, int):
        raise TypeError("argparse did not produce an int for --repeat")
    runner_class = namespace.runner_class
    if runner_class is not None and not isinstance(runner_class, str):
        raise TypeError("argparse did not produce text for --runner-class")
    raw_workloads: object = namespace.workload
    workloads: tuple[str, ...] | None
    if raw_workloads is None:
        workloads = None
    elif isinstance(raw_workloads, list):
        raw_values = cast(list[object], raw_workloads)
        values = [value for value in raw_values if isinstance(value, str)]
        if len(values) != len(raw_values):
            raise TypeError("argparse did not produce text values for --workload")
        workloads = tuple(values)
    else:
        raise TypeError("argparse did not produce a list for --workload")
    return Options(
        compiler=namespace.compiler,
        resource_root=namespace.resource_root,
        output=namespace.output,
        repeat=namespace.repeat,
        build_compiler=not bool(namespace.no_build),
        runner_class=runner_class,
        workloads=workloads,
    )


def main(arguments: Sequence[str] | None = None) -> int:
    args = parse_args(arguments)
    if args.repeat < 1:
        raise SystemExit("--repeat must be at least 1")
    runner_class = args.runner_class.strip() if args.runner_class is not None else None
    if args.runner_class is not None and not runner_class:
        raise SystemExit("--runner-class must not be empty")
    compiler = args.compiler.resolve()
    resource_root = args.resource_root.resolve()
    if not resource_root.joinpath("toolchain.meta").is_file():
        raise SystemExit(f"resource root is invalid: {resource_root}")
    if args.build_compiler and compiler == DEFAULT_COMPILER.resolve():
        subprocess.run(
            [
                "cargo",
                "build",
                "--release",
                "-p",
                "nia-cli",
                "--features",
                "perf-alloc",
            ],
            cwd=ROOT,
            check=True,
        )
    if not compiler.is_file():
        raise SystemExit(f"compiler does not exist: {compiler}")

    with tempfile.TemporaryDirectory(prefix="nia-perf-") as temporary:
        available = workloads(Path(temporary))
        selected = args.workloads or tuple(available)
        unknown = sorted(set(selected) - set(available))
        if unknown:
            raise SystemExit(f"unknown workload(s): {', '.join(unknown)}")
        results: list[JsonObject] = []
        for iteration in range(args.repeat):
            for name in selected:
                print(f"perf: iteration {iteration + 1}/{args.repeat} {name}", file=sys.stderr)
                try:
                    report = run_workload(
                        compiler, resource_root, name, available[name]
                    )
                except (RuntimeError, ValueError) as error:
                    raise SystemExit(f"error: {error}") from None
                report["iteration"] = iteration
                results.append(report)

    revision = command_output(["git", "rev-parse", "HEAD"])
    dirty = command_output(["git", "status", "--porcelain"])
    baseline: CompilerBaseline = {
        "schema_version": 1,
        "compiler": {
            "path": command_label(str(compiler)),
            "resource_root": command_label(str(resource_root)),
            "version": command_output([str(compiler), "--version"]),
            "revision": revision,
            "dirty": bool(dirty),
        },
        "machine": machine_metadata(runner_class),
        "repeat": args.repeat,
        "results": results,
    }
    output = args.output.resolve()
    output.parent.mkdir(parents=True, exist_ok=True)
    temporary_output = output.with_suffix(output.suffix + ".tmp")
    temporary_output.write_text(
        json.dumps(baseline, indent=2, sort_keys=True) + "\n", encoding="utf-8"
    )
    temporary_output.replace(output)
    print(output)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
