[package]
name = "nia-monomorphize"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true

[dependencies]
nia-ast.workspace = true
nia-body-ir.workspace = true
nia-comptime-check.workspace = true
nia-defs.workspace = true
nia-diagnostic.workspace = true
nia-ids.workspace = true
nia-item-signatures.workspace = true
nia-layout.workspace = true
nia-mangle.workspace = true
nia-sema-ir.workspace = true
nia-span.workspace = true
nia-trait-solve.workspace = true
nia-ty.workspace = true
nia-type-normalize.workspace = true

[dev-dependencies]
nia-node-id.workspace = true
nia-parser.workspace = true
nia-source.workspace = true

[lib]
path = "src/lib.rs"
