[package]
name = "nia-executable-reachability"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true

[dependencies]
nia-defs.workspace = true
nia-executable-facts.workspace = true
nia-hash.workspace = true
nia-ids.workspace = true
nia-item-signatures.workspace = true
nia-sema-ir.workspace = true
nia-span.workspace = true
nia-symbol.workspace = true
nia-timing.workspace = true
nia-ty.workspace = true
nia-type-lower.workspace = true
nia-type-normalize.workspace = true

[lib]
path = "src/lib.rs"
