[package]
name = "nia-cli"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true

[dependencies]
nia-build.workspace = true
nia-driver.workspace = true
nia-ice.workspace = true
nia-loader-query.workspace = true
nia-linker.workspace = true

[[bin]]
name = "nia"
path = "src/main.rs"
