[package]
name = "nia-cli"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true

[dependencies]
nia-codegen-llvm.workspace = true
nia-diagnostic.workspace = true
nia-driver.workspace = true
nia-ice.workspace = true
nia-ids.workspace = true
nia-imports.workspace = true
nia-lexer.workspace = true
nia-opt.workspace = true
nia-parser.workspace = true
nia-source.workspace = true

[[bin]]
name = "nia"
path = "src/main.rs"
