[package]
name = "nia-executable-facts"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true

[dependencies]
nia-body-ir.workspace = true
nia-defs.workspace = true
nia-ids.workspace = true
nia-sema-ir.workspace = true
nia-span.workspace = true
nia-symbol.workspace = true
nia-static-ir.workspace = true
nia-ty.workspace = true
nia-type-lower.workspace = true
nia-type-normalize.workspace = true

[dev-dependencies]
nia-ast.workspace = true

[lib]
path = "src/lib.rs"
