[package]
name = "nia-linker"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true

[dependencies]
nia-backend-ir.workspace = true
nia-query.workspace = true
nia-target-config.workspace = true
nia-toolchain.workspace = true

[dev-dependencies]
nia-source.workspace = true

[lib]
path = "src/lib.rs"
