[package]
name = "nia-compiler-query"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true

[dependencies]
nia-abi-check.workspace = true
nia-ast.workspace = true
nia-ast-walk.workspace = true
nia-backend-ir.workspace = true
nia-backend-lower.workspace = true
nia-body-check.workspace = true
nia-body-ir.workspace = true
nia-comptime-check.workspace = true
nia-comptime-ir.workspace = true
nia-defs.workspace = true
nia-diagnostic.workspace = true
nia-executable-facts.workspace = true
nia-executable-reachability.workspace = true
nia-flow-check.workspace = true
nia-function-ir.workspace = true
nia-function-lower.workspace = true
nia-ids.workspace = true
nia-imports.workspace = true
nia-item-tree.workspace = true
nia-item-signatures.workspace = true
nia-layout.workspace = true
nia-local-resolve.workspace = true
nia-monomorphize.workspace = true
nia-node-id.workspace = true
nia-opt.workspace = true
nia-parser.workspace = true
nia-program-signatures.workspace = true
nia-provider-summary.workspace = true
nia-query.workspace = true
nia-sema-ir.workspace = true
nia-source.workspace = true
nia-span.workspace = true
nia-static-check.workspace = true
nia-syntax.workspace = true
nia-target-config.workspace = true
nia-timing.workspace = true
nia-ty.workspace = true
nia-trait-solve.workspace = true
nia-type-lower.workspace = true
nia-type-normalize.workspace = true
nia-type-resolve.workspace = true
nia-value-resolve.workspace = true

[lib]
path = "src/lib.rs"
