[package]
name = "nia-driver"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true

[dependencies]
nia-compiler-query.workspace = true
nia-imports.workspace = true
nia-opt.workspace = true
nia-loader-query.workspace = true

[dev-dependencies]
nia-ast.workspace = true
nia-backend-ir.workspace = true
nia-body-ir.workspace = true
nia-function-ir.workspace = true
nia-ids.workspace = true
nia-layout.workspace = true
nia-static-ir.workspace = true
nia-ty.workspace = true

[lib]
path = "src/lib.rs"
